# Generated by Django 3.2.8 on 2021-11-16 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Plants',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('temperature', models.IntegerField()),
                ('elevation', models.IntegerField()),
                ('pic', models.ImageField(default='obviousplant.jpg', upload_to='plants/')),
            ],
        ),
    ]
